# Generated by Django 2.1.3 on 2018-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=2000)),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'ordering': ('title',),
            },
        ),
    ]
